require("gitsigns").setup({
  signs = {
    add = { text = "" },
    change = { text = "󰦓" },
    delete = { text = "󰍵" },
    topdelete = { text = "‾" },
    changedelete = { text = "~" },
    untracked = { text = "󰘓" },
  },
  signs_staged = {
    add = { text = "" },
    change = { text = "󰦓" },
    delete = { text = "󰍵" },
    topdelete = { text = "‾" },
    changedelete = { text = "~" },
    untracked = { text = "󰘓" },
  },
  signs_staged_enable = true,
  signcolumn = true,
  numhl = true,
  linehl = true,
  word_diff = false,
  watch_gitdir = { follow_files = true },
  auto_attach = true,
  attach_to_untracked = false,
  current_line_blame = true,
  current_line_blame_opts = {
    virt_text = true,
    virt_text_pos = "eol",
    delay = 500,
    ignore_whitespace = false,
    virt_text_priority = 100,
    use_focus = true,
  },
  current_line_blame_formatter = "<author> (<author_time:%Y-%m-%d %H:%M>) - <summary>",
  sign_priority = 6,
  update_debounce = 100,
  max_file_length = 40000,
  preview_config = { style = "minimal", relative = "cursor", row = 0, col = 1 },
})
-- Hunk-navigation keymaps live in lua/config/keymaps.lua (<leader>gj/gk, ]h/[h,
-- <leader>gh{s,r,p,b}) so all daily-driver keys are in one place.
